:hardbreaks:
:scrollbar:
:data-uri:
:toc3:
:showdetailed:
:linkattrs:
:noaudio:

== Configuration and Credential Management Patterns in Distributed Application


** ***Set the `user` specific variables***

----
user=<user-id>
----

==  Create the Project in OpenShift to deploy the Email Service

----
oc new-project $user-msinfra-demo
----

**  ***Deploy and Configure the `MySQL` backend for the `Email` Service***

** Create the Credential Required for the MySQL DB as a `Secret` object 
----
oc create secret generic mysql-secret --from-literal=MYSQL_DATABASE=microservices --from-literal=MYSQL_PASSWORD=password --from-literal=MYSQL_USER=app_user  --from-literal=MYSQL_ROOT_PASSWORD=password --from-literal=MYSQL_SERVICE_HOST=MYSQL
----
** ***Deploy the MySQL App*** 
----
oc new-app --name=mysql -lapp=mysql -lmicroservice=emailsvc --docker-image=docker.io/vinoalex/mysql-56-rhel
----

** Provide the Credentails defined in the `Secret` (mysql-secret) to the MySQL Pods 
----
oc env dc/mysql --from=secret/mysql-secret
----

== Deploy and Configure the Email Service App

** Create the `Configuration` Parameters required for the `Email` App [ Using `--from-literal` method ]
----
oc create configmap mail-config --from-literal=EMAIL_APPLICATION_DOMAIN="http://emailsvc:8080"
----
----
oc create secret generic email-secret --from-literal=GMAIL_USERNAME=devconfocp@gmail.com --from-literal=GMAIL_PASSWORD=XirZVyDjVvodKnMXDGwsw4JJsrzKpTby
----

** ***Create the `Configuration` Parameters (sql commands to create the `emails` table)as a ConfigMap  required for the `init` container of the `Email Service` deployment***


*** The `init` container will use ths configuration (sql commands in the file)to create the  `emails` tables in the 'microservices` database created in the MySQL app. 

** The init container of the `Email Service PoD` will mount the `myquery` ConfigMap as a `volume` with name `sql` on the path `/opt/sql`.

*** The `mysql` command is defined to consume its `args` from the `myquery` drive mount on `/opt/sql`

----
oc create configmap myquery --from-file=my.sql
----

****Please note;Here the ConfigMap is created using the  `--from-file` method***

** **Deploy the `Email App` from the `DeploymentConfiguration` manifest**

****You may view the deployment configuration manifest file `emailsvc.yaml` and find the use of the `secret` object `mysql-secret` in the configuration. Shairing within the same `namespace` is an  important feature of  ConfigMap and Secret` objects***

----
oc create -f myservice.yaml
----

** Verify the status of the  PoDs of the Project

----
oc get po
----

==  Create the Project in OpenShift to deploy the TwitterAPI and User Registration  Services

** ***Set the `user` specific variables***

----
user=<user-id>
----

** ***Create the Project***

----
oc new-project $user-msservices-demo
----

** Create the Credential Required for the mongodb as a `Secret` object
----
oc create secret generic mongo-secret --from-literal MONGODB_ADMIN_PASSWORD=password --from-literal MONGODB_DATABASE=userdb  --from-literal MONGODB_PASSWORD=password --from-literal MONGODB_USER=mongouser
----
** ***Deploy the Mongodb` App***
----
oc new-app --name mongodb -lmicroservice=userregsvc --docker-image=docker.io/vinoalex/mongodb
----
** Provide the Credentails defined in the `Secret` (mongo-secret)  to the `mongodb` Pods as Environment variables
----
oc env dc/mongodb --from=secret/mongo-secret
----

** Create the Credential Required for the twitter-api app  as a `Secret` object
----
oc create secret generic twitter-secret  --from-literal=TWITTER_CONSUMER_KEY=nothing  --from-literal=TWITTER_CONSUMER_SERVICE=nothing  --from-literal=TWITTER_OAUTH_ACCESS_TOKEN=nothing  --from-literal=TWITTER_OAUTH_ACCESS_TOKEN_SECRET=nothing
----
** ***Deploy the twitter-api App*** 
----
oc new-app --name=twitter-api -lmicroservice=twittersvc --docker-image=docker.io/vinoalex/twitter-api
----

** Provide the Credentails defined in the `Secret` (twitter-secret)  to the `twitter-api` Pods as Environment variables
----
oc env dc/twitter-api --from=secret/twitter-secret
----

** Create the external `route` to access the `twitter-api` App

----
oc expose svc/twitter-api
----

** Varify the `route` of the  twitter-api app
----
oc get route
----
** Create the Credential Required for the `User Registration Service` app  as a `Secret` object
----
oc create secret generic userregsvc-db --from-literal=MONGODB_USER=mongouser --from-literal=MONGODB_PASSWORD=password --from-literal MONGODB_DATABASE=userdb --from-literal=DATABASE_SERVICE_NAME=mongodb
----
** Create the Configuration Parameters  Required for the `User Registration Service` app  as a `ConfigMap` object
----
oc create configmap mail-config --from-literal=EMAIL_APPLICATION_DOMAIN="http://emailsvc.$user-msinfra-demo.svc.cluster.local:8080"
----

** ***Deploy the User Registrion Service App***
----
oc new-app --name=userregsvc -lmicroservice=userregsvc --docker-image=docker.io/vinoalex/userregsvc
----
** Provide the Credentails defined in the `Secret` (userregsvc-db)  to the `userregsvc` Pods as Environment variables
----
oc env dc/userregsvc --from=configmap/mail-config
----
** Provide the Credentails defined in the `Secret` (userregsvc-db)  to the `userregsvc` Pods as Environment variables
----
oc env dc/userregsvc --from=secret/userregsvc-db
----
** Create the external `route` to access the `userregsvc` App
----
oc expose svc/userregsvc
----
** Varify the `route` of the  userregsvc app
----
oc get route
----

** Verify the status of the  PoDs of the Project

----
oc get po
----


== Create the Project in OpenShift to deploy the `User Registration UI` App

** ***Set the `user` specific variables***

----
user=<user-id>
----

** ***Create the Project***

----
oc new-project $user-msclient-demo
----
** Create the Configuration Parameters Required for the `User Registration UI` app  as a `ConfigMap` object
----
oc create configmap userreg-config --from-literal=USER_REG_SVC="http://userregsvc.$user-msservices-demo.svc.cluster.local:8080" --from-literal=TWITTER_FEED_SVC="http://twitter-api.$user-msservices-demo.svc.cluster.local:8080"
----
----
oc create configmap userreg-config --from-literal=USER_REG_SVC="http://`oc get route -lapp=userregsvc -n $user-msservices-demo -o=custom-columns=:.spec.host| sed "1 d"`" --from-literal=TWITTER_FEED_SVC="http://`oc get route -lapp=twitter-api -n $user-msservices-demo -o=custom-columns=:.spec.host | sed "1 d"`"
----

** ***Deploy the `user registration UI` App***
----
oc new-app --name='userreg' -l microservice=userreg --docker-image=docker.io/vinoalex/usereg
----
** Provide the Credentails defined in the `Secret` (userreg-config)  to the `userreg` Pods as Environment variables
----
oc env dc/userreg --from=configmap/userreg-config
----

** Create the external `route` to access the `userregsvc` App
----
oc expose svc/userreg
----

** Varify the `route` of the  userregsvc app
----
oc get route 
----
** Access the `route` url from the Web Browser

== Scale the `User Registration UI` App (Increase the PoD Instances)

----
oc scale dc/userreg --replicas=4
----
** Create a new user registration and verify the App function

